name: main_symmetrics
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.6+26

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  carousel_slider: ^4.1.1
  flutter_spinkit: ^5.1.0
  provider: ^6.0.4
  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  iconsax: ^0.0.8
  fluttertoast: ^8.1.1
  entry: ^0.0.7
  image_downloader: ^0.31.0
  custom_navigation_bar: ^0.8.2
  permission_handler: ^10.2.0
  rename: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  photo_view: ^0.14.0
  wallpaper_manager_flutter: ^0.0.2
  shared_preferences: ^2.0.15
  flutter_cache_manager: ^3.3.0
  image_cropper: ^3.0.1
  palette_generator: ^0.3.3+2
  url_launcher: ^6.1.6
  native_notify:
  firebase_crashlytics:
  firebase_analytics:
  firebase_core:
  firebase_messaging:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
   - assets/app_logo.png

